name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CGO_LDFLAGS: "-Lstorage/possum/lib/target/debug -lpossum"
    strategy:
      matrix:
        go-version: ["1.24"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Build possum
        run: |
          cd storage/possum/lib
          cargo build --lib
      - run: go test -race -bench . -benchtime 2x ./...

        # Test on 386 for atomic alignment and other bad 64-bit assumptions
      - run: GOARCH=386 go test -run @ ./...
      - name: Some packages compile for WebAssembly
        run: GOOS=js GOARCH=wasm go build . ./storage ./tracker/...
      - run: |
          brew install macfuse pv md5sha1sum bash
      - run: |
          # Need master for cross-compiling fix
          go install -v -x github.com/anacrolix/godo@v1
          echo $PATH
          sudo apt install pv fuse
          GOARCH=386 fs/test.sh
          mount
