name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CGO_LDFLAGS: storage/possum/lib/target/debug/libpossum.a
    strategy:
      matrix:
        go-version: ["1.24"]
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Build possum
        run: |
          cd storage/possum/lib
          cargo build --lib
      # Separate to remove downloading spam and possible caching improvement.
      - run: go mod download
      - run: go test -race ./...
      # Separate benchmarks because I think it modifies the stderr handling.
      - run: go test -race -bench . -benchtime 2x -run @ ./...

        # Test on 386 for atomic alignment and other bad 64-bit assumptions
      - if: matrix.os != 'macos-latest'
        run: GOARCH=386 go test -run @ ./...
      - name: Some packages compile for WebAssembly
        run: GOOS=js GOARCH=wasm go build . ./storage ./tracker/...
      - run: brew install macfuse pv md5sha1sum bash
        if: matrix.os == 'macos-latest'
      - run: sudo apt install pv fuse
        if: matrix.os == 'ubuntu-latest'
      - run: |
          go install github.com/anacrolix/godo@v1
          echo $PATH
      - run: |
          GOARCH=386 fs/test.sh
          mount
